# Generated by Django 5.0.7 on 2024-07-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comment_blog_remove_comment_author_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='author',
            new_name='name',
        ),
    ]
