# Generated by Django 5.0.7 on 2024-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_body_info_message_rename_author_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
