# Generated by Django 5.0.7 on 2024-07-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_info_message_alter_info_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
