# Generated by Django 5.0.7 on 2024-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indeximage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog-img/')),
            ],
        ),
    ]
