# Generated by Django 5.0.7 on 2024-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog_img2/')),
                ('name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=12)),
                ('category', models.TextField()),
            ],
        ),
    ]
