# Generated by Django 5.0.7 on 2024-07-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='index_banner/')),
                ('category', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('title', models.TextField()),
            ],
        ),
    ]
