# Generated by Django 5.0.7 on 2024-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_index_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_banner',
            name='title',
            field=models.TextField(max_length=15),
        ),
    ]
